"""added received at and receiver fields to quantitative test order

Revision ID: 37e10eef9eb4
Revises: 827ecc994026
Create Date: 2020-03-29 21:34:48.728848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e10eef9eb4'
down_revision = '827ecc994026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_quan_test_orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lab_quan_test_orders', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lab_quan_test_orders', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_quan_test_orders', 'user', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_quan_test_orders', type_='foreignkey')
    op.drop_column('lab_quan_test_orders', 'receiver_id')
    op.drop_column('lab_quan_test_orders', 'received_at')
    op.drop_column('lab_quan_test_orders', 'cancelled_at')
    # ### end Alembic commands ###
