"""added lab ID field to the choice set model

Revision ID: 75b5d3c5ec65
Revises: dfcc2d6763ab
Create Date: 2020-03-29 14:44:04.325676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b5d3c5ec65'
down_revision = 'dfcc2d6763ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_result_choice_set', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_result_choice_set', 'labs', ['lab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_result_choice_set', type_='foreignkey')
    op.drop_column('lab_result_choice_set', 'lab_id')
    # ### end Alembic commands ###
