"""replaced test ID with order ID in the record set model

Revision ID: 791d13932547
Revises: bf54ff492b3d
Create Date: 2020-04-13 06:23:20.967139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791d13932547'
down_revision = 'bf54ff492b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_quan_result_sets', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_constraint('lab_quan_result_sets_test_id_fkey', 'lab_quan_result_sets', type_='foreignkey')
    op.create_foreign_key(None, 'lab_quan_result_sets', 'lab_quan_test_orders', ['order_id'], ['id'])
    op.drop_column('lab_quan_result_sets', 'test_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_quan_result_sets', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lab_quan_result_sets', type_='foreignkey')
    op.create_foreign_key('lab_quan_result_sets_test_id_fkey', 'lab_quan_result_sets', 'lab_quan_tests', ['test_id'], ['id'])
    op.drop_column('lab_quan_result_sets', 'order_id')
    # ### end Alembic commands ###
