"""added LabQuanTestOrder model

Revision ID: 827ecc994026
Revises: 42bb15550ff4
Create Date: 2020-03-29 20:53:33.320412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827ecc994026'
down_revision = '42bb15550ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_quan_test_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['lab_customers.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_quan_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_quan_test_orders')
    # ### end Alembic commands ###
