"""added deactivated datetime field

Revision ID: 90eae0b2ee67
Revises: 025127af31cf
Create Date: 2025-08-20 14:11:09.845709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eae0b2ee67'
down_revision = '025127af31cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lab_affils', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lab_affils', schema=None) as batch_op:
        batch_op.drop_column('deactivated_at')

    # ### end Alembic commands ###
