"""added finished at field to the order model

Revision ID: 94eaa99e6291
Revises: 791d13932547
Create Date: 2020-04-13 07:37:21.880313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94eaa99e6291'
down_revision = '791d13932547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_qual_result_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['lab_qual_test_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_qual_result_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_set_id', sa.Integer(), nullable=True),
    sa.Column('text_result', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('updator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_set_id'], ['lab_qual_result_sets.id'], ),
    sa.ForeignKeyConstraint(['updator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lab_qual_test_orders', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_qual_test_orders', 'finished_at')
    op.drop_table('lab_qual_result_records')
    op.drop_table('lab_qual_result_sets')
    # ### end Alembic commands ###
