"""added new user-lab affiliation model

Revision ID: 95050386efbe
Revises: c98a02543ef5
Create Date: 2020-03-29 11:46:05.855498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95050386efbe'
down_revision = 'c98a02543ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lab_affils',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lab_id')
    )
    op.drop_table('user_labs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_labs',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], name='user_labs_lab_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_labs_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'lab_id', name='user_labs_pkey')
    )
    op.drop_table('user_lab_affils')
    # ### end Alembic commands ###
