"""added finished_at field to the order

Revision ID: bf54ff492b3d
Revises: 850f202a2940
Create Date: 2020-04-13 05:38:40.575358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf54ff492b3d'
down_revision = '850f202a2940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_quan_test_orders', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_quan_test_orders', 'finished_at')
    # ### end Alembic commands ###
