"""added a ref field to the choice set model

Revision ID: c546b5edf35a
Revises: 81d7378b4244
Create Date: 2020-03-29 15:35:29.749281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c546b5edf35a'
down_revision = '81d7378b4244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_result_choice_set', sa.Column('reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_result_choice_set', 'reference')
    # ### end Alembic commands ###
