"""added the creator ID field to the lab model

Revision ID: c98a02543ef5
Revises: c5f329459174
Create Date: 2020-03-29 10:54:50.830790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98a02543ef5'
down_revision = 'c5f329459174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'labs', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.drop_column('labs', 'creator_id')
    # ### end Alembic commands ###
