"""added approver and approve datetime for result record

Revision ID: d306f038a381
Revises: f916ffe745e0
Create Date: 2023-10-26 23:27:06.758526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd306f038a381'
down_revision = 'f916ffe745e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_qual_result_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['approver_id'], ['id'])

    with op.batch_alter_table('lab_quan_result_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['approver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_quan_result_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approver_id')
        batch_op.drop_column('approved_at')

    with op.batch_alter_table('lab_qual_result_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approver_id')

    # ### end Alembic commands ###
