"""added lab ID field

Revision ID: dfcc2d6763ab
Revises: cc356d76f061
Create Date: 2020-03-29 14:16:07.624420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcc2d6763ab'
down_revision = 'cc356d76f061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_quan_tests', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_quan_tests', 'labs', ['lab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_quan_tests', type_='foreignkey')
    op.drop_column('lab_quan_tests', 'lab_id')
    # ### end Alembic commands ###
