"""added several quantitative test-related models

Revision ID: e875ba6cb2ce
Revises: 95050386efbe
Create Date: 2020-03-29 14:00:32.259015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e875ba6cb2ce'
down_revision = '95050386efbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_result_choice_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_quan_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(), nullable=True),
    sa.Column('max_value', sa.Numeric(), nullable=True),
    sa.Column('min_ref_value', sa.Numeric(), nullable=True),
    sa.Column('max_ref_value', sa.Numeric(), nullable=True),
    sa.Column('choice_set', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['choice_set'], ['lab_result_choice_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_result_choice_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('choices_id', sa.Integer(), nullable=True),
    sa.Column('ref', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['choices_id'], ['lab_result_choice_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_quan_result_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['lab_quan_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_quan_result_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_set_id', sa.Integer(), nullable=True),
    sa.Column('num_result', sa.Numeric(), nullable=True),
    sa.Column('text_result', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('updator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_set_id'], ['lab_quan_result_sets.id'], ),
    sa.ForeignKeyConstraint(['updator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_quan_result_records')
    op.drop_table('lab_quan_result_sets')
    op.drop_table('lab_result_choice_item')
    op.drop_table('lab_quan_tests')
    op.drop_table('lab_result_choice_set')
    # ### end Alembic commands ###
