"""added reject record model

Revision ID: f916ffe745e0
Revises: 94eaa99e6291
Create Date: 2020-04-20 02:10:53.821247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f916ffe745e0'
down_revision = '94eaa99e6291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_order_reject_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lab_qual_test_orders', sa.Column('reject_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_qual_test_orders', 'lab_order_reject_records', ['reject_record_id'], ['id'])
    op.add_column('lab_quan_test_orders', sa.Column('reject_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_quan_test_orders', 'lab_order_reject_records', ['reject_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_quan_test_orders', type_='foreignkey')
    op.drop_column('lab_quan_test_orders', 'reject_record_id')
    op.drop_constraint(None, 'lab_qual_test_orders', type_='foreignkey')
    op.drop_column('lab_qual_test_orders', 'reject_record_id')
    op.drop_table('lab_order_reject_records')
    # ### end Alembic commands ###
